# config.yaml

# 1) Elasticsearch connection
es_host: localhost
es_port: 9200

# 2) ElastAlert writeback index
writeback_index: elastalert_status

# 3) Where your rule files live
rules_folder: rules

# 4) When to run
run_every:
  seconds: 10

# How far back to look for events in each run
buffer_time:
  seconds: 30

# 5) Default timestamp field in your docs
timestamp_field: timestamp

# 6) Don’t try to print alerts by default
alert_text_type: alert_text_only
