version: "3.9"

services:
  api:
    build: ./docker/php
    container_name: eab-api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    environment:
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: eab
      DB_USERNAME: eab
      DB_PASSWORD: sql1234
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: eab-nginx
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  mysql:
    image: mysql:8.3
    container_name: eab-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eab
      MYSQL_USER: eab
      MYSQL_PASSWORD: sql1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
