filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/lib/postgresql/16/main/pg_log/postgresql-*.log
      - /var/lib/postgresql/16/main/pg_log/postgresql-*.csv
    fields:
      type: postgresql
    fields_under_root: true

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "postgresql-logs-%{+yyyy.MM.dd}"

setup.template.name: "postgresql-logs-%{+yyyy.MM.dd}"
setup.template.pattern: "postgresql-logs-*"
setup.template.enabled: true
setup.template.overwrite: true

logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
